import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

/**
 * The root layout component.
 *
 * @param {React.PropsWithChildren} root0 - The props.
 * @param {React.ReactNode} root0.children - The children.
 * @returns {JSX.Element} The root layout component.
 */
export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
